name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Build and Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan cache:clear
          php artisan optimize

      - name: Prepare public directory
        run: |
          mkdir -p htdocs
          cp -r public/* htdocs/
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./htdocs
          remote-dir: /htdocs
          exclude: |
            */.git
            */.github
            */node_modules
            */dist
          dry-run: false